/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author camilo
 */
public class PanelSeleccion extends javax.swing.JPanel {

    int numero;
    /**
     * Creates new form Produccion
     */
    private PanelSeleccion() {
        initComponents();
    }
    
    public PanelSeleccion(int numero){
        initComponents();
        this.numero = numero;
        setNumero(numero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jtfSeleccion = new javax.swing.JTextField();
        btnFinSecuencia = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout(1, 0));

        lblNombre.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        lblNombre.setText("Selección(#) = ");

        jtfSeleccion.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

        btnFinSecuencia.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        btnFinSecuencia.setText("˧");
        btnFinSecuencia.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnFinSecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinSecuenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinSecuencia)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jtfSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblNombre)
                .addComponent(btnFinSecuencia))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinSecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinSecuenciaActionPerformed
        // TODO add your handling code here:
        if(btnFinSecuencia.isSelected()){
            jtfSeleccion.setText(jtfSeleccion.getText() + "˧");
            jtfSeleccion.setEditable(false);
        } else {
            quitarFinSecuencia();
            jtfSeleccion.setEditable(true);
        }
    }//GEN-LAST:event_btnFinSecuenciaActionPerformed

    private void setNumero(int numero) {
        lblNombre.setText("Seleccion(" + numero + ")");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFinSecuencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfSeleccion;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

    private void quitarFinSecuencia(){
        String seleccion = jtfSeleccion.getText();
        seleccion = seleccion.substring(0, seleccion.length()-1);
        jtfSeleccion.setText(seleccion);
    }
}
