/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Lista.Conjunto;
import gramatica.NoTerminal;
import gramatica.Produccion;
import javax.swing.JOptionPane;

/**
 *
 * @author camilo
 */
public class PanelProduccion extends javax.swing.JPanel {

    private int numero;
    private String anteriorDefinicion;

    /**
     * Creates new form Produccion
     */
    public PanelProduccion() {
        initComponents();
    }

    public PanelProduccion(Produccion produccion) {
        initComponents();
        jtfNoTerminal.setText(produccion.getParteIzquierda().toString());
        jtfDefinicion.setText(produccion.getDefinicion().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbSeleccionado = new javax.swing.JCheckBox();
        lblNumero = new javax.swing.JLabel();
        jtfNoTerminal = new javax.swing.JTextField();
        txtFlecha = new javax.swing.JLabel();
        jtfDefinicion = new javax.swing.JTextField();
        btnLambda = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout(1, 0));

        lblNumero.setText("1.");

        jtfNoTerminal.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jtfNoTerminal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFlecha.setText("->");

        jtfDefinicion.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

        btnLambda.setText("λ");
        btnLambda.setMargin(new java.awt.Insets(2, 7, 2, 7));
        btnLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLambdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbSeleccionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNoTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFlecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDefinicion, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLambda)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSeleccionado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumero)
                        .addComponent(jtfNoTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFlecha)
                        .addComponent(jtfDefinicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLambda))))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLambdaActionPerformed
        // TODO add your handling code here:
        if (btnLambda.isSelected()) {
            anteriorDefinicion = jtfDefinicion.getText();
            jtfDefinicion.setText("λ");
            jtfDefinicion.setEditable(false);
        } else {
            jtfDefinicion.setText(anteriorDefinicion);
            jtfDefinicion.setEditable(true);
        }
    }//GEN-LAST:event_btnLambdaActionPerformed

    public void setNumero(int numero) {
        lblNumero.setText(numero + ".");
    }

    public boolean isSelected() {
        return cbSeleccionado.isSelected();
    }

    public void setSelected(boolean opt) {
        cbSeleccionado.setSelected(opt);
    }

    public int getNumero() {
        return numero;
    }

    public String getNombreNoTerminal() {
        return jtfNoTerminal.getText();
    }

    public Produccion getProduccion() {
        Produccion produccion = new Produccion();
        produccion.setParteIzquierda(new NoTerminal(jtfNoTerminal.getText()));
        Conjunto definicion = new Conjunto();
        String definicionTexto = jtfDefinicion.getText();
        String noTerminal = "";
        boolean abierto = false;
        for (int i = 0; i < definicionTexto.length(); i++) {
            if (!abierto) {
                if (definicionTexto.charAt(i) == '<') {
                    abierto = true;
                    noTerminal = "";
                } else if (definicionTexto.charAt(i) == '>') {
                    JOptionPane.showMessageDialog(this, "Error", "Error en la producción " + getNumero(), JOptionPane.ERROR_MESSAGE);
                    return null;
                } else {
                    definicion.agregar(definicionTexto.charAt(i));
                }
            } else {
                if (definicionTexto.charAt(i) == '>') {
                    abierto = false;
                    if (!"".equals(noTerminal)) {
                        definicion.agregar(new NoTerminal(noTerminal));
                    }
                } else if (definicionTexto.charAt(i) == '<') {
                    JOptionPane.showMessageDialog(this, "Error", "Error en la producción " + getNumero(), JOptionPane.ERROR_MESSAGE);
                    return null;
                } else {
                    noTerminal = noTerminal + definicionTexto.charAt(i);
                }
            }
        }
        produccion.setDefinicion(definicion);
        return produccion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLambda;
    private javax.swing.JCheckBox cbSeleccionado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfDefinicion;
    private javax.swing.JTextField jtfNoTerminal;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel txtFlecha;
    // End of variables declaration//GEN-END:variables

}
